services:
  db:
    image: postgres:15
    container_name: plato-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plato-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: plato-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - plato-network

  socket:
    build:
      context: .
      dockerfile: ./apps/socket/Dockerfile
    container_name: plato-socket
    ports:
      - "3001:3001"
    networks:
      - plato-network

networks:
  plato-network:
    driver: bridge

volumes:
  postgres_data:
