version: "3.8"

services:
  db:
    image: postgres:15
    container_name: carta-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carta-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: carta-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carta
      - DIRECT_URL=postgresql://postgres:postgres@db:5432/carta
      - SOCKET_URL=http://socket:3001
    depends_on:
      - db
    networks:
      - carta-network

  socket:
    build:
      context: .
      dockerfile: ./apps/socket/Dockerfile
    container_name: carta-socket
    ports:
      - "3001:3001"
    networks:
      - carta-network

networks:
  carta-network:
    driver: bridge

volumes:
  postgres_data:
