import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ToasterProvider } from '@/providers/toaster-provider'
import ModalsProviders from '@/providers/modals-provider'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Carta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}
        style={{
          backgroundImage: 'url(./background-2.png)',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'cover',
          backgroundAttachment: 'fixed',
        }}
      >
        <ToasterProvider />
        <ModalsProviders />
        {children}
      </body>
    </html>
  )
}
